### ISSUE TITLE
option to disable/bypass hlint?

### ISSUE THREAD

**Issue by goolord** [juhp/hkgr#1]
hlint is useful, but it's not good enough to be the gatekeeper to hackage

**Comment by juhp** [comment]
Oops I missed this - I can add an option I guess or just make it an informational prompt.

**Comment by juhp** [comment]
Sorry I took so long to push this - going to make a new release shortly anyway.
I think hlint doesn't block uploading, so it is mostly informational.

Do report if you have more feedback, thanks

**Comment by juhp** [comment]
The new option is in 0.4.
