### ISSUE TITLE
Please don't test hkgr in "production"

### ISSUE THREAD

**Issue by phadej** [juhp/hkgr#2]
There are now 4 releases made in 45 minutes. That can be considered spamming.

> Guidelines for Hackage Packages:
>
> - Packages cannot be deleted, so you should consider uploading new package versions as package candidates and testing before publishing to the main index.

EDIT: Consider this issues as a request to make `hkgr` upload *package candidates by default* (or even *only*)

**Comment by juhp** [comment]
I just saw this comment/feedback now.
hkgr does upload candidates first by default: there was no malicious intent.
